trigger:
- master

name: 1.0.$(Rev:r)

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  BQC.ForceNewBaseline: false

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 6'
  inputs:
    version: 6.0.x
    includePreviewVersions: false

- task: DotNetCoreCLI@2
  displayName: 'Restore nuget packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '1e7423eb-2859-4a5e-862e-9a80a3cf889d'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-c $(buildConfiguration) --no-restore /p:Version=$(Build.BuildNumber) /p:NoWarn=0618'
    versioningScheme: 'byBuildNumber'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--collect "Code coverage" --configuration $(buildConfiguration) --no-build'

- task: BuildQualityChecks@8
  displayName: 'Build Quality Checks'
  inputs:
    checkWarnings: true
    warningFailOption: 'build'
    allowWarningVariance: true
    warningVariance: '1'
    checkCoverage: true
    coverageFailOption: 'build'
    coverageType: 'blocks'
    allowCoverageVariance: true
    coverageVariance: '1'

- task: DotNetCoreCLI@2
  displayName: 'Pack nuget Eplicta.Mhtml'
  inputs:
    command: 'pack'
    packagesToPack: 'Eplicta.Mhtml/Eplicta.Mhtml.csproj'
    nobuild: true
    versioningScheme: 'byBuildNumber'

- task: NuGetCommand@2
  displayName: 'Push nuget packages to nuget.org'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget.org'
